import type { Metadata } from "next";
import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'
import TanStackProvider from '@/components/TanStackProvider/TanStackProvider'


export const metadata: Metadata = {
title: "Create Next App",
description: "Generated by create next app",};

export default function RootLayout ({
children,
}: Readonly<{
children: React.ReactNode;}>){
return (
<html lang="en">
      <body>
        <TanStackProvider>
          <Header />
          {children}
          <Footer />
        </TanStackProvider>
      </body>
    </html>
  )
}
